version: '3'
services:
  backend:
    build: devsync-backend
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
        - devsync
  frontend:
    build: devsync-frontend
    ports:
      - "3000:5173"

  db:
    container_name: devsync_db
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: devsync_db
    ports:
      - "3310:3306"
    networks:
        - devsync
    volumes:
      - ./db:/var/lib/mysql
networks:
  devsync:
    driver: bridge


